### ISSUE TITLE
Application to GitHub Accelerator 2024

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#132]
## Intro

Some time ago we registered our interest in the GitHub Accelerator. Now we should fill out the full application form (below).
@pavlovcik Please give your input on this application

**From my point of view, Ubiquity can fit into such categories:**
- Marketplaces and tools that democratize access to AI
- AI powered developer applications and tools

As far as I understand, it will be possible to integrate AI into each of the Ubiquity DAO OS (UbiquiBot) plugins. Ubiquity DAO OS and DevPool act as a marketplace that will have AI functionality.

### The invitation

> We are excited to announce that [GitHub Accelerator opened applications](https://accelerator.github.com/) for its second cohort. Selected participants receive up to $40,000 in funding and programming to accelerate open source projects, and build careers or companies.
This year’s theme is open source AI because the pace of innovation and development is rapidly accelerating. GitHub wants to invite people and projects that are building AI based solutions under an open source license to improve the world around them to apply.
If you or a project you know is interested, please apply by March 5 12PM PST.
The program will kick-off April 22 for our 10 week peer-based cohort program filled with instruction, workshops, discussion, projects, and mentorship.

>Program details 
The 10-week Accelerator program will kick off on April 22 and include a mix of 1-to-1, group sessions, project work, and mentorships. Participants will also receive:
$40,000 per project in non-dilutive funding.
5-10 hours per week of live instruction, workshops, and homework.
Office Hours with the GitHub team for security reviews.
Q&As with enterprise GitHub Sponsors, community members, and GitHub leaders.
Introduction to, and at least one office hour with, M12, Microsoft’s Venture Fund. 
Free access to relevant GitHub products, including a full year of GitHub Copilot.
Eligible projects will receive free Azure AI infrastructure credits including preferred access to high-end GPU virtual machine clusters and white glove go-to-market support.
A shared slack channel with your cohort to collaborate and support each other.
Thanks,
GitHub Accelerator Team

### Information from the GitHub resources

**Links**
https://accelerator.github.com/
https://github.com/sponsors
https://docs.github.com/en/sponsors/getting-started-with-github-sponsors/about-github-sponsors#supported-regions-for-github-sponsors

**Supported regions for GitHub Sponsors**

Among supported: 
- South Korea
- United States

Not supported: 
- BVI

**FAQ**

>How many projects will be selected? What are you looking for? Who decides who is selected?
We will select 10 projects for the cohort. All of our applications will be evaluated by a selection committee. You’ll be much more likely to be selected if you:
Have an active and growing set of users
Understand how you want to grow and maintain your project
Wish to pursue open source work full-time

>We are interested in projects working in the open focused on:
AI Developers Tools and Infrastructure and Pipeline
Models and frameworks, including architectures
Hardware and hardware enablement
Data and data infrastructure
Marketplaces and tools that democratize access to AI
AI powered developer applications and tools
Cyber security

## 2024 GitHub Accelerator Application

- Email
- What is your first name?
- What is your last name?
- What is your GitHub Handle (e.g. @mona)?
- City
- State or Province
- Country
- What is your project?
- Sum up your project in under 5 sentences.
- What open source license are you using?
- What is your approximate community stage?
- What is the projects GitHub repo? Please enter the project repo's GitHub URL
- Please enter any URLs of websites or social media accounts associated with your project (if applicable).
- Are there other contributors to this project who want to join the GitHub Accelerator with you? What is their GitHub handle?
- Why do you want to be in open source full-time?
- What is your role and level of involvement in the project?
- What is your ideal funding strategy (e.g., enterprise sponsors, foundation grants, starting a company, venture capital)?
- How much money have you raised so far?
- Do you have an existing sponsorship strategy?
- Do you self-identify as an underrepresented person in tech? Please share.

By checking this box you agree that you must:
- Be age eighteen (18) or older;
- Be a current maintainer of an open source project on GitHub;.
- Have an active online profile on GitHub;
- Reside in one of the regions supported by [GitHub Sponsors](https://github.com/sponsors)
- Not be a current employee or contractor of GitHub and/or any of its parent/subsidiary companies (including Microsoft);
- Have an active and growing set of users as determined by GitHub;
- Understand how you want to grow and maintain your project.
- Agree to [Code of Conduct](https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct) and [Privacy Statement](https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement).

**Comment by 0x4007** [comment]
![image](https://github.com/ubiquity/research/assets/4975670/6079b0a6-53e1-4a72-9ae4-505b87b9a1e9)

I have a screen recording of my responses from my phone that includes my doxed information I can share upon request

**Comment by 0x4007** [comment]
I thought that this blurb was interesting to explain the project 

> A GitHub bot with a fully extensible architecture that allows technical leadership to codify direct financial incentives for distributed teams to contribute to their repositories or organizations on GitHub. 

> This system allows teams to create (or select from existing) custom incentive schemas for their contributors in order to increase engagement and reduce team management overhead, especially useful for globally distributed teams who work asynchronously (like ours!)

> This system also enables a global and open contributor pool (the “DevPool”) filled with per contributor performance analytics and a global XP leaderboard, all directly tied to their real contributions on GitHub, in order to optimally match talent to newly opened issues within our network of partners (utilizing AI vector embeddings!)

> These selling points are all implemented as separate plugins for our bot, but out-of-the-box we offer infrastructure to automatically set prices for issues and directly pay contributors for their contributions (with granular per-contributor tracking down to every on-issue-topic word they write in comments of issues) instantly when the issue is closed as completed; and we are actively researching alternative payout methods including our very own DevPool debit card.

**Comment by 0x4007** [comment]
I feel like this is a coin toss working about half the time at this point. Hopefully we can get our conversation incentives!

**Comment by 0x4007** [comment]
Testing to see if it will work with assignee incentive as well.

**Comment by 0x4007** [comment]
I guess it would have been wise for me to post my full responses here in order to get credit. Note to future self as I start to participate more in this system for end-to-end testing purposes.

**Comment by sergfeldman** [comment]
Thank you! Claimed

**Comment by sergfeldman** [comment]
@pavlovcik Since this year's GitHub Accelerator program is dedicated to AI, it is advisable to place more emphasis on AI.
I think it is important to fully comply with at least 1 specific category:
- **AI powered** developer applications and tools
- Marketplaces and tools that **democratize access to AI**

For GitHub, our system can be called OS OS - Open Source Operating System.
Describe the system as a Copilot for Open Source organizations to orchestrate the entire development lifecycle on GitHub.
The value is productivity - motivating contributors and increasing the manageability of distributed teams creating Open Source projects on GitHub.
Mention, that the system itself is Open Source, modular, and powered with AI agents.
A part of the system is an AI-enhanced marketplace that facilitates the development of Open Source projects on GitHub.

If you wish, we can compile one more application to GitHub Accelerator.

**Comment by 0x4007** [comment]
> @pavlovcik Since this year's GitHub Accelerator program is dedicated to AI, it is advisable to place more emphasis on AI.
I think it is important to fully comply with at least 1 specific category:

I guess I could have laid it on more thick- I only made references to using AI (like embeddings.)

> If you wish, we can compile one more application to GitHub Accelerator.

Okay that's probably a good idea

I just OCR'd from the video recording:

- 2024 GitHub
- Accelerator
- Application
- Submitting an application is required to be considered for the program.
- Draft saved
- * Indicates required question
- Email *
- What is your first name? *
- What is your last name? *
- What is your GitHub Handle (e.g. @mona)?
- @pavlovcik
- City
- 10634
- Seoul
- State or Province
- Country
- Korea
- What is your project?
- DevPool by Ubiquity
- sum up your project in under 5 sentences.
- A GitHub bot with a fully extensible architecture that allows technical leadership to codify direct financial incentives for distributed teams to contribute to their repositories or organizations on GitHub.
- This system allows teams to create (or select from existing) custom incentive schemas for their contributors in order to increase engagement and reduce team management overhead, especially useful for globally distributed teams who work asynchronously (like ours!)
- This system also enables a global and open contributor pool (the "DevPool") filled with per contributor performance analytics and a global XP leaderboard, all directly tied to their real contributions on GitHub, in order to optimally match talent to newly opened issues within our network of partners (utilizing Al vector embeddings!)
- These selling points are all implemented as separate plugins for our bot, but out-of-the-box we offer infrastructure to automatically set prices for issues and directly pay contributors for their contributions (with granular per-contributor tracking down to every on-issue-topic word they write in comments of issues or linked pull requests) instantly when the issue is closed as completed; and we are actively researching alternative payout methods including our very own DevPool debit card.
- What open source license are you using?
- MIT
- What is your approximate community stage?
- 101-1000 users
- What is the projects GitHub repo? Please enter the project repo's GitHub URL
- https://github.com/ubiquity/ubiquibot
- Please enter any URLs of websites or * social media accounts associated with your project (if applicable).
- I want to make a special note that the repository above will soon be deprecated in favor of@ubiquity/ubiquibot-kernel
- We also have a ton of other repositories directly related to this infrastructure.
- Including, but not limited to:
- @ubiquity/work.ubq.fi
- @ubiquity/pay.ubq.fi
- @ubiquity/devpool-directory @ubiquibot/comment-incentives
- We have a simple bot account that reposts the priced issues from within our network (only us now)
- https://twitter.com/ubiquitydevpool
- For our hiring process we ask that contributors use this system to serve as a
- "paid technical interview" and the landing page is https://dao.ubq.fi/devpool
- Are there other contributors to this project who want to join the GitHub Accelerator with you? What is their GitHub handle?
- We have several contributors on salary at our organization working on this infrastructure now, with immediate plans to hire more full timers.
- We would essentially allocate the whole development team to the project during the course of the accelerator. You may be able to see the active contributors at our organization for a better idea of who will be involved: https://github.com/ubiquity
- Why do you want to be in open source full-time?
- I like to remove as many barriers as possible to innovation. I think that open source is a fantastic model to harness the talent and brainpower from all over the world to build the best products.
- What is your role and level of involvement in the project?
- Founder, full time. I lead many of the r&d efforts for the infrastructure that we are building for this system.
- What is your ideal funding strategy (e.g., enterprise sponsors, foundation grants, starting a company, venture capital)?
- We are well capitalized but we are looking for every possibility to officially partner with GitHub and/or Microsoft via a small capital infusion and/or to help promote us.
- We closed our $2M USD seed round at $20M
- USD valuation in May 2022 and are beginning our series A fundraise between March and September of this year. Because we manage our operational costs efficiently (thanks to this system!) and due to effective treasury management, we still have $1.75M
- of the funds about a year and a half later.
- The series A's objective is primarily to forge strategic partnerships. We very much would like for GitHub/Microsoft to be on our capitalization table for this upcoming round.
- How much money have you raised so far?
- +$1,000,000 US
- Do you have an existing sponsorship strategy?
- Not sponsorship strategy but we have plans to monetize the system off of partners with a freemium model (I.e. charge for using premium plugins)

**Comment by sergfeldman** [comment]
@pavlovcik I`ve just realized that it might make sense to describe our solution in the same terms as GitHub named the categories interesting for them.
For example, Ubiquity builds an operation system with AI-powered developer tools and a task marketplace that democratizes access to AI for Open Source projects on GitHub.

In this case (realizing that this is some exaggeration):
- Ubiquity DAO OS Kernel (UbiquiBot Kernel) is the core of the system, the AI to which we give access (like AI repository Manager, AI Manager).
- Ubiquity DAO OS Plugins are AI-powered developer tools.
- DevPool is a task marketplace that gives access to AI.

Please let me know if you need my help with a description for GitHub.

**Comment by 0x4007** [comment]
> Ubiquity builds an operation system with

DAO Task Operating System

> Ubiquity DAO OS Plugins are AI-powered developer tools.

I think the most powerful application of plugins is to develop custom incentivization schemas for your organizations, using money or XP as currency. 

> Please let me know if you need my help with a description for GitHub.

Sure thing!

**Comment by sergfeldman** [comment]
Next version:
Ubiquity builds a DAO Task Operating System with AI-powered developer tools and a task marketplace.
Open Source projects on GitHub will benefit from a flexible framework for incentivizing contributors and democratizing access to AI.
