### ISSUE TITLE
AI agent systems to explore

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#141]
As Ubiquity is presented as an AI-powered system then VCs can compare Ubiquity with other Web3 AI agent systems.
It would be good to explore these systems. 

- Fetch
https://fetch.ai/
https://m.youtube.com/watch?v=I-B3_ujMmRI It can be useful to watch to formulate our strategy.

- Delysium
https://www.delysium.com/ 
https://www.delysium.com/about Microsoft among contributors.

- Olas
https://olas.network/ Provides DAO tooling, deployed on Gnosis Chain. 
https://www.valory.xyz/ 
>Creating open-source frameworks for co-owned AI

- Morpheus 
https://mor.org/
https://cryptodaily.co.uk/news-in-crypto/observers:morpheus-ai-locks-120m-to-fund-personal-smart-agent-platform-for-web3
https://www.linkedin.com/pulse/role-morpheusais-fair-launch-network-ai-agents-qyzve?trk=article-ssr-frontend-pulse_more-articles_related-content-card 

>Innovative Reward System: The platform incentivizes contributions across various roles, including capital providers, coders, compute providers, and community builders, through a token-based system that rewards participation and contribution to the Morpheus ecosystem

**Comment by 0x4007** [comment]
I think you should get into the habit of defining deliverables so that these tasks are actionable. I think that this research is immensely valuable for the purposes of the pitchdeck I'm working on now. Thanks!

### Fetch

- https://fetch.ai/integrations reminds me a lot of what we are doing with "plugins" 
- Because we are hyper specialized in software development, it should be far easier to provide more value within the context of software development specifically.
- Seems the most legit, they were founded in 2018 and raised a ton of cash. 
- The idea of setting up "tasks for agents" seem to be pretty mappable to our current approach with tasks. We could start with human agents, and then easily transition into AI agents for the exact same tasks system, although the scope of our tasks/speciality will be code related and we can experiment with outside of code things as well!
- They have an SDK so I could see a possible future where we build plugins using fetch.ai.
- I couldn't login to their site because I didn't have a "fetch wallet" this is very interesting that they have their own wallet. I also would be interested to make a deeper integration with our Dollars and Card via our own wallet one day.
- > [During each registration process, agents must prove ownership of their address.](https://fetch.ai/docs/references/contracts/uagents-almanac/almanac-overview)
   - Interesting strategy for us to potentially register wallets controlled by plugins.

### Delysium

> https://www.delysium.com/about Microsoft among contributors.

- I spent five minutes on their site lol I'm pretty certain they are embellishing the relationship, if any, with Microsoft and Google but I didn't find any definitive proof either way.
- According to Crunchbase they raised $14M from whatever investors. I get kind of grifter vibes because they are pushing how to buy and stake their tokens so much.


### Olas

- I know that they have some type of relationship with Gnosis Chain because they were retweeted. I actually rode their coin up from $1 -> $7! They've been on my radar since about $1 price. 
- https://olas.network/#ecosystem seems like a great idea for us to make a similar page. 
- The founder/ceo used to work at fetch.ai until 2021! https://www.linkedin.com/in/davidminarsch/

### Morpheus

- I don't see the value of this one.
- It seems like they just keep going on about "decentralized AI" and the ability for it to act on-chain (like Olas and Fetch) as well as making "agents"
- > User Data Security: Prioritising data security, Morpheus plans to adopt Fully Homomorphic Encryption (FHE) for LLMs, ensuring enhanced protection for user data within the peer-to-peer network.
   - lol
- > Unlike Autonolas, Morpheus differentiates itself with a decentralised and fair-launch approach (there was no pre-mine or early token sale).This strategy has attracted prominent supporters, including Eric Voorhees.
   - We also did this!
 - > Morpheus, though newer in the industry, has rapidly gained momentum with over 1,000 GitHub commits since mid-2023. While Autonolas exhibits a higher number of GitHub commits, indicating extensive development, Morpheus is in the process of establishing its market position. 
   - I bet our GitHub activity is on par or more.  So far from what I see at https://github.com/MorpheusAIs definitely. 
---

I think one point to highlight is that our vision might be less abstract because we already have functional infrastructure that we are benefiting from.

**Comment by sergfeldman** [comment]
This is a single AI developer (not a system) https://www.cognition-labs.com/blog

**Comment by sergfeldman** [comment]
>I think you should get into the habit of defining deliverables so that these tasks are actionable.

Yes, thanks for the recommendation.

>I think that this research is immensely valuable for the purposes of the pitchdeck I'm working on now. Thanks!

It’s very cool that you have already reviewed information about these platforms!

My vision of the research deliverable is to have a short list of AI agent systems to monitor and take the best experience from.
This list of 4 companies was obtained as a result of a high-level analysis of hundreds of “AI companies” and a selection of more or less similar to AI agent systems.

We can use this list this way:

1) Assess the positioning of these companies and take the best things for our Series A materials.
First of all, I recommend watching this Fetch interview https://m.youtube.com/watch?v=I-B3_ujMmRI

2) Use their valuation as references in negotiations with VCs.
For example, Morpheus AI locked the valuation of $120M in February 2024 https://cryptodaily.co.uk/news-in-crypto/observers:morpheus-ai-locks-120m-to-fund-personal-smart-agent-platform-for-web3
This could help value Ubiquity at a similar level.

3) Consider cooperation with some of them.
For example, the way you wrote about Fetch
>They have an SDK so I could see a possible future where we build plugins using fetch.ai.

**Comment by 0x4007** [comment]
> This is a single AI developer (not a system) https://www.cognition-labs.com/blog

I signed up for their waitlist

**Comment by sergfeldman** [comment]
Thank you, claimed

**Comment by sergfeldman** [comment]
@pavlovcik They claim to build OS for agents
https://github.com/AgentOps-AI/agentops

**Comment by 0x4007** [comment]
> @pavlovcik They claim to build OS for agents https://github.com/AgentOps-AI/agentops

This is so vague to me I have no idea what the value is. It talks about "time travel debugging" etc but I don't understand the original problems its trying to solve.
