### ISSUE TITLE
ubq.fi copywriting strategy

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/research#40]
we should empasize devpool more and figure out the balance between it and our stablecoin

- this should be delivered as a pull request to the updated landing page.

> landing page

> marketing stuff on "normie" landing page with a big call to action "read the technical docs" to our notion for our cto type counterparties.

copywriting reference https://github.com/orgs/ubiquity/projects/24/views/3?pane=issue&itemId=32464996

**Comment by Hodlatoor** [comment]
@pavlovcik need help?

**Comment by Hodlatoor** [comment]
do you want me to pick up this bounty?  is DevPool our defining thing now?

**Comment by 0x4007** [comment]
I only realized about an hour ago that I had notifications disabled for this repo lol sorry for all the late replies. 

Yes it would be helpful if you can do this @Hodlatoor

**Comment by Hodlatoor** [comment]
> I only realized about an hour ago that I had notifications disabled for this repo lol sorry for all the late replies. 
> 
> Yes it would be helpful if you can do this @Hodlatoor 

okay let's set up the bounty and apply to me. I'll take care of it.

**Comment by Hodlatoor** [comment]
@pavlovcik @sergfeldman Let me know what you think of this. The intent is to keep it short and descriptive. balancing out the original narrative with our points of focus now and then going full circle.

Imagine this as the main page intro:
-------------


**u·biq·ui·ty** : the fact of appearing everywhere. 
At Ubiquity DAO we aim to keep true to our name. We strive to be everywhere in Crypto by providing genuine value and utility. That is our vision. 

There are many opportunities in the crypto space. A lot of tools, methods and processes are being developed. Many more have yet to have been thought of. As a builder DAO we see many of these opportunities and realize that an experienced responsible development path is necessary. Not just for us but for the industry we are part of.  
In order to be everywhere the first step is to build. We build tools that people need and marketplaces that people want.  

**The uAD Stablecoin:**
We began our Ubiquitous journey by entering the nascent world of blockchain and crypto backed gaming. We envisioned a Stablecoin that will be used on many games, projects and initiatives. We prodigiously began to build the model, Tokenomics and secure infrastructure and then we built it again uAD was born. uAD will be instrumental to all the future projects we will deploy. Including DevPool. 

**Enter DevPool:**
As our DAO grew we realized that the decentralized nature of DAOs, like Ubiquity, necessitated a new platform. 
A marketplace where we can call upon specialized talent, on demand, to help solve our problems. Not only was it a rethink of the hiring process, it was an organic extension to the way DAOs and the future of crypto will work. We soon realized it is also a sustainable model for how DAOs can optimally operate. This is where we embarked on building our first grand contribution to the crypto environment: The DevPool.


The DevPool can be considered both a marketplace and a DAO OS. 

**As a marketplace:** DevPool enables DAOs to work smoother and develop faster. DevPool allows contributors to help build both horizontally and vertically based on their interest and get paid for their contributions. It is a marketplace where need meets supply.

**As an OS:** DevPool helps keep DAOs and project managers focused on their mission and deliverables. This is the OS component. Built on top of GitHub and integrating our extensible Ubiquibot AI, DevPool allows project managers to optimize their resources and collaborate with effective, results focused, talent to build and deploy their projects. 

Being built on top of GitHub means that DevPool enjoys all the features that are organic to GitHub and by extension it means that we can deploy the best of DAO models to also support existing web2 projects as well as future crypto development on GitHub. 

We are actively seeking out strategic partnerships with the leading names in the space alongside GitHub and Microsoft including Optimism, Gnosis and W3F to name a few. We already have existing relationships with Animoca, Merit Circle, Momentum6 and other prominent industry leaders. 

Once DevPool is deployed and we assure critical mass adoption we will continue to build additional tools and marketplaces to realize our goal of Ubiquity.

**Comment by Hodlatoor** [comment]
@pavlovcik 
https://github.com/ubiquity/ubq.fi/blob/main/index.html
line 76 is where i think we should place this content. I am not sure if there are other versions contemplated for mobile or not. I would prefer someone who recently worked with this file and the mobile issue append the main page content to avoid unnecessary issues..

**Comment by Hodlatoor** [comment]
content still needs to be made live

**Comment by 0x4007** [comment]
> You need to finish the work, deliver it, and pass review to be eligible for bounties. If you don't complete this process then you are not eligible to collect bounties.

Due to the repeated violations of unauthorized funding and collecting bounties without reviews, your elevated permissions to close issues have been revoked. 

- Skipped Review <sup><a href="https://github.com/ubiquity/business-development/issues/35#issuecomment-1623128125">1</a></sup> <sup><a href="https://github.com/ubiquity/business-development/issues/35#issuecomment-1623187669">2</a></sup> <sup><a href="https://github.com/ubiquity/business-development/issues/38#issuecomment-1653564466">3</a></sup> <sup><a href="https://github.com/ubiquity/research/issues/40#issuecomment-1685271800">4</a></sup> <sup><a href="https://github.com/ubiquity/business-development/issues/60#issuecomment-1637052565">5</a></sup> 
- Unauthorized Funding <sup><a href="https://github.com/ubiquity/business-development/issues/1#issuecomment-1519066362">1</a></sup> <sup><a href="https://github.com/ubiquity/business-development/issues/2#issuecomment-1498477795">2</a></sup>

**Comment by Hodlatoor** [comment]
> > You need to finish the work, deliver it, and pass review to be eligible for bounties. If you don't complete this process then you are not eligible to collect bounties.
> 
> Due to the repeated violations of unauthorized funding and collecting bounties without reviews, your elevated permissions to close issues have been revoked. 
> 
> - Skipped Review <sup><a href="https://github.com/ubiquity/business-development/issues/35#issuecomment-1623128125">1</a></sup> <sup><a href="https://github.com/ubiquity/business-development/issues/35#issuecomment-1623187669">2</a></sup> <sup><a href="https://github.com/ubiquity/business-development/issues/38#issuecomment-1653564466">3</a></sup> <sup><a href="https://github.com/ubiquity/research/issues/40#issuecomment-1685271800">4</a></sup> <sup><a href="https://github.com/ubiquity/business-development/issues/60#issuecomment-1637052565">5</a></sup> 
> - Unauthorized Funding <sup><a href="https://github.com/ubiquity/business-development/issues/1#issuecomment-1519066362">1</a></sup> <sup><a href="https://github.com/ubiquity/business-development/issues/2#issuecomment-1498477795">2</a></sup>
> 


What is this? i'm responsible for these deliverables and properly executed them.
