### ISSUE TITLE
Proposal to define approach to GitHub Next 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#73]
### Context 

View [on Telegram](https://t.me/UbiquityDAO/29361/30987).

> アレクサンダー.eth | U B I Q U I T Y, [8/18/2023 1:46 AM]
> I just realized that we probably would have a really good shot at building a relationship with “GitHub Next”
> 
> I’m checking out @rserr’s research at https://github.com/ubiquity/research/issues/58#issuecomment-1668713199 and he mentioned https://githubnext.com/projects/copilot-for-pull-requests/
> 
> @Jonjonjg u think u can lead the charge?
> 
> J G, [8/18/2023 4:46 AM]
> sure.  are we looking at this for a personality enhancement with AI suggestions for ghost text or for copilot for PR? just setup the bounty and I will get it situated.
> 
> アレクサンダー.eth | U B I Q U I T Y, [8/18/2023 12:48 PM]
> github next seems to be an elite team at github that focuses on experimental features to enhance github. i think our bot has a handful of features that could be presented to them as something they might be able to support in some capacity, like promoting on their page or grants
> 
> J G, [8/18/2023 12:51 PM]
> Can I get a list of the top hooks currently available for them and future development and I will take a look / reach out

### Define approach

**Contact**

We should check whether they are active now. 

- They are not active on Twitter https://twitter.com/githubnext
- Check their Discord https://discord.com/invite/FeGshJZ2yy
- We can tag team members on GitHub https://githubnext.com/#team

For tagging on GitHub we can use 
1. Alex's idea - go to their personal repos and post comments there.
2. Create a bounty, describe what we want from them, and tag all of them in the description like "Request for comments".

**Proposal** 

Define our proposal to GitHub Next as an entity that should be discussed.
It can be 
- Payouts - crypto, others to be defined 
- AI features - to be defined

The proposal to the GitHub Next individual team members can be 
- Please provide positive and negative feedback on our product from GitHub's point of view.
- Please connect us with someone in GiHub who might be interested in our product.
- Please recommend how to develop our product more efficiently from the point of view of GitHub.
- As developers have experience with GitHub and AI, please recommend effective ways to use AI in our product.

**Comment by 0x4007** [comment]
Suggestion: for the context segment, you should link back to the original [Telegram message](https://t.me/UbiquityDAO/29361/30987), and place the content as quotes to make it clear that it's not original material you are writing for the specification.

This is a lovely proposal thanks for putting this together. Perhaps we can put together a little video. This is probably the most comfortable form of content consumption.

> Payouts - crypto, others to be defined

- We should reference as much as we can about their [GitHub Sponsors](https://github.com/sponsors) program because this is a loose parallel to our payments now. 
- We can lightly touch on that we plan to have first party support for banking and debit cards.

> AI features - to be defined

- https://github.com/ubiquity/ubiquibot/discussions/107 Roadmap of originally planned AI powered features.
- https://github.com/ubiquity/ubiquibot/issues/488 We are almost done with "duplicate issue handling" which is very useful from a utility standpoint! 
- https://github.com/ubiquity/telegram-ubiquibot/issues/2 We also have a more experimental AI that listens for delegated tasks and places them on GitHub for issue tracking.
